name: spider_chart_examples
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  spider_chart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  screenshots: ^2.1.1
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
